# -*- coding: utf-8 -*-

env = Environment(
    CPPPATH=['../src/core',
             '../src/auto',
             '../src/os/unix',
    ],
    CFLAGS=['-g',
            '-Wall',
            #'-O2',
    ],
    LIBS=[
          'pthread',
          'crypt',
          'pcre',
          'crypto',
          'z',
    ],
)

targets = {
    "string" : ["string.c",  '../libngxcore.a'],
    "regex"  : ["regex.c",   '../libngxcore.a'],
    "pool"   : ["pool.c",    '../libngxcore.a'],
    "temp"   : ["temp.c",    '../libngxcore.a'],
    "version": ["version.c", '../libngxcore.a'],
    "parse"  : ["parse.c",   '../libngxcore.a'],
    "array"  : ["array.c",   '../libngxcore.a'],
    "md5"    : ["md5.c",     '../libngxcore.a'],
    "crc32"  : ["crc32.c",   '../libngxcore.a'],
    "list"   : ["list.c",    '../libngxcore.a'],
    "time"   : ["time.c",    '../libngxcore.a'],
    }

[ env.Program(target, targets[target]) for target in targets ]
