# -*- coding: utf-8 -*-

env = Environment(
    CPPPATH=['../src/core',
             '../src/auto',
             '../src/os/unix',
    ],
    CFLAGS=['-g',
            '-Wall',
            #'-O2',
    ],
    LIBS=[
          'pthread',
          'crypt',
          'pcre',
          'crypto',
          'z',
    ],
)

targets = {
    "string" : ["string.c"],
    "regex"  : ["regex.c"],
    "pool"   : ["pool.c"],
    "temp"   : ["temp.c"],
    "version": ["version.c"],
    "parse"  : ["parse.c"],
    "array"  : ["array.c"],
    "md5"    : ["md5.c"],
    "sha1"   : ["sha1.c"],
    "crc32"  : ["crc32.c"],
    "base64" : ["base64.c"],
    "list"   : ["list.c"],
    "time"   : ["time.c"],
    "hash"   : ["hash.c"],
    }
[ targets[target].append('../libngxcore.a') for target in targets ]

[ env.Program(target, targets[target]) for target in targets ]
